export const FETCH_SECTIONS = 'FETCH_SECTIONS';
export const FETCH_SECTIONS_START = 'FETCH_SECTIONS_START';
export const FETCH_SECTIONS_SUCCESS = 'FETCH_SECTIONS_SUCCESS';
export const FETCH_SECTIONS_FAIL = 'FETCH_SECTIONS_FAIL';

export const FETCH_MOVIE = 'FETCH_MOVIE';
export const FETCH_MOVIE_START = 'FETCH_MOVIE_START';
export const FETCH_MOVIE_SUCCESS = 'FETCH_MOVIE_SUCCESS';
export const FETCH_MOVIE_FAIL = 'FETCH_MOVIE_FAIL';
export const CLEAR_MOVIE = 'CLEAR_MOVIE';

export const INIT_PLAYER = 'INIT_PLAYER';
export const SHOW_PLAYER = 'SHOW_PLAYER';
export const LOAD_PLAYER = 'LOAD_PLAYER';
export const HIDE_PLAYER = 'HIDE_PLAYER';
export const ERROR_PLAYER = 'ERROR_PLAYER';