export const FETCH_CONTENTS = 'FETCH_CONTENTS';
export const FETCH_CONTENTS_START = 'FETCH_CONTENTS_START';
export const FETCH_CONTENTS_SUCCESS = 'FETCH_CONTENTS_SUCCESS';
export const FETCH_CONTENTS_FAIL = 'FETCH_CONTENTS_FAIL';